name: Erlang CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:
    strategy:
      matrix:
        otp-version: [23.3.4.5, 24.1.3, latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.otp-version }}

    container:
      image: erlang:${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit
